export const START_FETCH_ANNOUCEMENT = 'START_FETCH_ANNOUCEMENT';
export const SUCCESS_FETCH_ANNOUCEMENT = 'SUCCESS_FETCH_ANNOUCEMENT';
export const ERROR_FETCH_ANNOUCEMENT = 'ERROR_FETCH_ANNOUCEMENT';

export const START_FETCH_ANNOUCEMENT_DETAIL = 'START_FETCH_ANNOUCEMENT_DETAIL';
export const SUCCESS_FETCH_ANNOUCEMENT_DETAIL =
  'SUCCESS_FETCH_ANNOUCEMENT_DETAIL';
export const ERROR_FETCH_ANNOUCEMENT_DETAIL = 'ERROR_FETCH_ANNOUCEMENT_DETAIL';
