export const START_ATTENDACES = 'START_ATTENDACES';
export const SUCCESS_ATTENDACES = 'SUCCESS_ATTENDACES';
export const ERROR_ATTENDACES = 'ERROR_ATTENDACES';

export const START_ATTENDACES_DETAIL = 'START_ATTENDACES_DETAIL';
export const SUCCESS_ATTENDACES_DETAIL = 'SUCCESS_ATTENDACES_DETAIL';
export const ERROR_ATTENDACES_DETAIL = 'ERROR_ATTENDACES_DETAIL';
