export const START_SUBMISSIONS = 'START_SUBMISSIONS';
export const SUCCESS_SUBMISSIONS = 'SUCCESS_SUBMISSIONS';
export const ERROR_SUBMISSIONS = 'ERROR_SUBMISSIONS';

export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const CLEAR_START_DATE_END_DATE = 'CLEAR_START_DATE_END_DATE';

export const START_SUBMISSIONS_DETAIL = 'START_SUBMISSIONS_DETAIL';
export const SUCCESS_SUBMISSIONS_DETAIL = 'SUCCESS_SUBMISSIONS_DETAIL';
export const ERROR_SUBMISSIONS_DETAIL = 'ERROR_SUBMISSIONS_DETAIL';
