export const START_SUBMISSIONS = 'START_SUBMISSIONS';
export const SUCCESS_SUBMISSIONS = 'SUCCESS_SUBMISSIONS';
export const ERROR_SUBMISSIONS = 'ERROR_SUBMISSIONS';

export const START_SUBMISSIONS_DETAIL = 'START_SUBMISSIONS_DETAIL';
export const SUCCESS_SUBMISSIONS_DETAIL = 'SUCCESS_SUBMISSIONS_DETAIL';
export const ERROR_SUBMISSIONS_DETAIL = 'ERROR_SUBMISSIONS_DETAIL';

export const START_CATEGORY_SUBMISSIONS = 'START_CATEGORY_SUBMISSIONS';
export const SUCCESS_CATEGORY_SUBMISSIONS = 'SUCCESS_CATEGORY_SUBMISSIONS';
export const ERROR_CATEGORY_SUBMISSIONS = 'ERROR_CATEGORY_SUBMISSIONS';
