export const START_FETCH_PROFILE = 'START_FETCH_PROFILE';
export const SUCCESS_FETCH_PROFILE = 'SUCCESS_FETCH_PROFILE';
export const ERROR_FETCH_PROFILE = 'ERROR_FETCH_PROFILE';

export const START_UPDATE_PROFILE = 'START_UPDATE_PROFILE';
export const SUCCESS_UPDATE_PROFILE = 'SUCCESS_UPDATE_PROFILE';
export const ERROR_UPDATE_PROFILE = 'ERROR_UPDATE_PROFILE';

export const RESET_FORM_PROFILE = 'RESET_FORM_PROFILE';
