export const ON_PRESS_MENU_ITEM = 'ON_PRESS_MENU_ITEM';
export const RESET_VALUE_BOTTOM_SHEET = 'RESET_VALUE_BOTTOM_SHEET';

// form cuti
export const TOOGLE_PICKER_END_DATE = 'TOOGLE_PICKER_END_DATE';
export const ONCHANGE_TEXT_END_DATE = 'ONCHANGE_TEXT_END_DATE';
export const CONFIRM_END_DATE = 'CONFIRM_END_DATE';
export const ONCHANGE_DEFAULT_VALUE_END_DATE =
  'ONCHANGE_DEFAULT_VALUE_END_DATE';
export const TOOGLE_PICKER_START_DATE = 'TOOGLE_PICKER_START_DATE';
export const ONCHANGE_TEXT_START_DATE = 'ONCHANGE_TEXT_START_DATE';
export const CONFIRM_START_DATE = 'CONFIRM_START_DATE';
export const ONCHANGE_DEFAULT_VALUE_START_DATE =
  'ONCHANGE_DEFAULT_VALUE_START_DATE';

// form izin
export const TOOGLE_PICKER_END_DATE_PERMISSION =
  'TOOGLE_PICKER_END_DATE_PERMISSION';
export const ONCHANGE_TEXT_END_DATE_PERMISSION =
  'ONCHANGE_TEXT_END_DATE_PERMISSION';
export const CONFIRM_END_DATE_PERMISSION = 'CONFIRM_END_DATE_PERMISSION';
export const ONCHANGE_DEFAULT_VALUE_END_DATE_PERMISSION =
  'ONCHANGE_DEFAULT_VALUE_END_DATE_PERMISSION';
export const TOOGLE_PICKER_START_DATE_PERMISSION =
  'TOOGLE_PICKER_START_DATE_PERMISSION';
export const ONCHANGE_TEXT_START_DATE_PERMISSION =
  'ONCHANGE_TEXT_START_DATE_PERMISSION';
export const CONFIRM_START_DATE_PERMISSION = 'CONFIRM_START_DATE_PERMISSION';
export const ONCHANGE_DEFAULT_VALUE_START_DATE_PERMISSION =
  'ONCHANGE_DEFAULT_VALUE_START_DATE_PERMISSION';
export const ONCHANGE_REASON_PERMISSION = 'ONCHANGE_REASON_PERMISSION';

// clockIn
export const CLOCK_IN = 'CLOCK_IN';
export const CLOCK_OUT = 'CLOCK_OUT';
export const CLOCK_IN_OVERTIME = 'CLOCK_IN_OVERTIME';
export const CLOCK_OUT_OVERTIME = 'CLOCK_OUT_OVERTIME';
