export const ON_PRESS_MENU_ITEM = 'ON_PRESS_MENU_ITEM';
export const RESET_VALUE_BOTTOM_SHEET = 'RESET_VALUE_BOTTOM_SHEET';

// form cuti
export const TOOGLE_PICKER_END_DATE = 'TOOGLE_PICKER_END_DATE';
export const ONCHANGE_TEXT_END_DATE = 'ONCHANGE_TEXT_END_DATE';
export const CONFIRM_END_DATE = 'CONFIRM_END_DATE';
export const ONCHANGE_DEFAULT_VALUE_END_DATE =
  'ONCHANGE_DEFAULT_VALUE_END_DATE';
export const TOOGLE_PICKER_START_DATE = 'TOOGLE_PICKER_START_DATE';
export const ONCHANGE_TEXT_START_DATE = 'ONCHANGE_TEXT_START_DATE';
export const CONFIRM_START_DATE = 'CONFIRM_START_DATE';
export const ONCHANGE_DEFAULT_VALUE_START_DATE =
  'ONCHANGE_DEFAULT_VALUE_START_DATE';

// form izin/permission
export const TOOGLE_PICKER_END_DATE_PERMISSION =
  'TOOGLE_PICKER_END_DATE_PERMISSION';
export const ONCHANGE_TEXT_END_DATE_PERMISSION =
  'ONCHANGE_TEXT_END_DATE_PERMISSION';
export const CONFIRM_END_DATE_PERMISSION = 'CONFIRM_END_DATE_PERMISSION';
export const ONCHANGE_DEFAULT_VALUE_END_DATE_PERMISSION =
  'ONCHANGE_DEFAULT_VALUE_END_DATE_PERMISSION';
export const TOOGLE_PICKER_START_DATE_PERMISSION =
  'TOOGLE_PICKER_START_DATE_PERMISSION';
export const ONCHANGE_TEXT_START_DATE_PERMISSION =
  'ONCHANGE_TEXT_START_DATE_PERMISSION';
export const CONFIRM_START_DATE_PERMISSION = 'CONFIRM_START_DATE_PERMISSION';
export const ONCHANGE_DEFAULT_VALUE_START_DATE_PERMISSION =
  'ONCHANGE_DEFAULT_VALUE_START_DATE_PERMISSION';
export const ONCHANGE_REASON_PERMISSION = 'ONCHANGE_REASON_PERMISSION';

// form pengajuan/submission
export const TOOGLE_PICKER_END_DATE_SUBMISSION =
  'TOOGLE_PICKER_END_DATE_SUBMISSION';
export const TOOGLE_PICKER_START_DATE_SUBMISSION =
  'TOOGLE_PICKER_START_DATE_SUBMISSION';
export const ONCHANGE_DEFAULT_VALUE_END_DATE_SUBMISSION =
  'ONCHANGE_DEFAULT_VALUE_END_DATE_SUBMISSION';
export const ONCHANGE_DEFAULT_VALUE_START_DATE_SUBMISSION =
  'ONCHANGE_DEFAULT_VALUE_START_DATE_SUBMISSION';
export const ONCHANGE_DESCRIPTION_SUBMISSION =
  'ONCHANGE_DESCRIPTION_SUBMISSION';
export const ONCHANGE_DEFAULT_VALUE_END_TIME_SUBMISSION =
  'ONCHANGE_DEFAULT_VALUE_END_TIME_SUBMISSION';
export const CONFIRM_START_DATE_SUBMISSION = 'CONFIRM_START_DATE_SUBMISSION';
export const CONFIRM_END_DATE_SUBMISSION = 'CONFIRM_END_DATE_SUBMISSION';

export const CONFIRM_END_TIME_SUBMISSION = 'CONFIRM_END_TIME_SUBMISSION';
export const CONFIRM_START_TIME_SUBMISSION = 'CONFIRM_START_TIME_SUBMISSION';

export const CHANGE_CATEOGRY_SUBMISSION = 'CHANGE_CATEOGRY_SUBMISSION';

export const CHANGE_FILE1_SUBMISSION = 'CHANGE_FILE1_SUBMISSION';
export const CHANGE_FILE2_SUBMISSION = 'CHANGE_FILE2_SUBMISSION';
export const REMOVE_FILE1_SUBMISSION = 'REMOVE_FILE1_SUBMISSION';
export const REMOVE_FILE2_SUBMISSION = 'REMOVE_FILE2_SUBMISSION';

export const START_SUBMIT_SUBMISSION = 'START_SUBMIT_SUBMISSION';
export const SUCCESS_SUBMIT_SUBMISSION = 'SUCCESS_SUBMIT_SUBMISSION';
export const ERROR_SUBMIT_SUBMISSION = 'ERROR_SUBMIT_SUBMISSION';

export const START_SUBMISSION_MINE = 'START_SUBMISSION_MINE';
export const SUCCESS_SUBMISSION_MINE = 'SUCCESS_SUBMISSION_MINE';
export const ERROR_SUBMISSION_MINE = 'ERROR_SUBMISSION_MINE';

export const RESET_STATE_SUBMISSION = 'RESET_STATE_SUBMISSION';

// clockIn
export const START_CLOCK_IN = 'START_CLOCK_IN';
export const ERROR_CLOCK_IN = 'ERROR_CLOCK_IN';
export const SUCCESS_CLOCK_IN = 'SUCCESS_CLOCK_IN';
export const RESET_STATE_CLOCK_IN = 'RESET_STATE_CLOCK_IN';

export const CLOCK_OUT = 'CLOCK_OUT';
export const CLOCK_IN_OVERTIME = 'CLOCK_IN_OVERTIME';
export const CLOCK_OUT_OVERTIME = 'CLOCK_OUT_OVERTIME';
//

// lembur/overtime
export const TOOGLE_PICKER_END_DATE_OVERTIME =
  'TOOGLE_PICKER_END_DATE_OVERTIME';

export const TOOGLE_PICKER_START_DATE_OVERTIME =
  'TOOGLE_PICKER_START_DATE_OVERTIME';

export const ONCHANGE_DEFAULT_VALUE_END_DATE_OVERTIME =
  'ONCHANGE_DEFAULT_VALUE_END_DATE_OVERTIME';

export const ONCHANGE_DEFAULT_VALUE_START_DATE_OVERTIME =
  'ONCHANGE_DEFAULT_VALUE_START_DATE_OVERTIME';

export const ONCHANGE_DESCRIPTION_OVERTIME = 'ONCHANGE_DESCRIPTION_OVERTIME';

export const ONCHANGE_DEFAULT_VALUE_END_TIME_OVERTIME =
  'ONCHANGE_DEFAULT_VALUE_END_TIME_OVERTIME';

export const CONFIRM_START_DATE_OVERTIME = 'CONFIRM_START_DATE_OVERTIME';

export const CONFIRM_END_DATE_OVERTIME = 'CONFIRM_END_DATE_OVERTIME';

export const CONFIRM_END_TIME_OVERTIME = 'CONFIRM_END_TIME_OVERTIME';

export const CONFIRM_START_TIME_OVERTIME = 'CONFIRM_START_TIME_OVERTIME';

export const CHANGE_CATEOGRY_OVERTIME = 'CHANGE_CATEOGRY_OVERTIME';

export const CHANGE_FILE1_OVERTIME = 'CHANGE_FILE1_OVERTIME';

export const REMOVE_FILE1_OVERTIME = 'REMOVE_FILE1_OVERTIME';

export const CHANGE_DEFAULT_VALUE_END_TIME = 'CHANGE_DEFAULT_VALUE_END_TIME';

export const CHANGE_DEFAULT_VALUE_START_TIME =
  'CHANGE_DEFAULT_VALUE_START_TIME';

export const START_SUBMIT_OVERTIME = 'START_SUBMIT_OVERTIME';
export const SUCCESS_SUBMIT_OVERTIME = 'SUCCESS_SUBMIT_OVERTIME';
export const ERROR_SUBMIT_OVERTIME = 'ERROR_SUBMIT_OVERTIME';

export const START_OVERTIME_MINE = 'START_OVERTIME_MINE';
export const SUCCESS_OVERTIME_MINE = 'SUCCESS_OVERTIME_MINE';
export const ERROR_OVERTIME_MINE = 'ERROR_OVERTIME_MINE';

export const RESET_STATE_OVERTIME = 'RESET_STATE_OVERTIME';

// absen attendace

export const START_ATTENDACE_MINE = 'START_ATTENDACE_MINE';
export const SUCCESS_ATTENDACE_MINE = 'SUCCESS_ATTENDACE_MINE';
export const ERROR_ATTENDACE_MINE = 'ERROR_SUBMIT_OVERTIME_MINE';
