export const START_OVERTIMES = 'START_OVERTIMES';
export const SUCCESS_OVERTIMES = 'SUCCESS_OVERTIMES';
export const ERROR_OVERTIMES = 'ERROR_OVERTIMES';

export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const CLEAR_START_DATE_END_DATE = 'CLEAR_START_DATE_END_DATE';
