export const START_GENERATE_FLPP = 'START_GENERATE_FLPP';
export const SUCCESS_GENERATE_FLPP = 'SUCCESS_GENERATE_FLPP';
export const ERROR_GENERATE_FLPP = 'ERROR_GENERATE_FLPP';
export const RESET_GENERATE_FLPP = 'RESET_GENERATE_FLPP';
export const RESET_STATUS_GENERATE_FLPP = 'RESET_STATUS_GENERATE_FLPP';
