export const START_CREATE_BOOKING = 'START_CREATE_BOOKING';
export const SUCCESS_CREATE_BOOKING = 'SUCCESS_CREATE_BOOKING';
export const ERROR_CREATE_BOOKING = 'ERROR_CREATE_BOOKING';
export const RESET_CREATE_BOOKING = 'RESET_CREATE_BOOKING';
export const RESET_STATUS_CREATE_BOOKING = 'RESET_STATUS_CREATE_BOOKING';

export const START_UPDATE_BOOKING = 'START_UPDATE_BOOKING';
export const SUCCESS_UPDATE_BOOKING = 'SUCCESS_UPDATE_BOOKING';
export const ERROR_UPDATE_BOOKING = 'ERROR_UPDATE_BOOKING';
export const RESET_UPDATE_BOOKING = 'RESET_UPDATE_BOOKING';
export const RESET_STATUS_UPDATE_BOOKING = 'RESET_STATUS_UPDATE_BOOKING';

export const START_REVIEW_ADM_BOOKING = 'START_REVIEW_ADM_BOOKING';
export const SUCCESS_REVIEW_ADM_BOOKING = 'SUCCESS_REVIEW_ADM_BOOKING';
export const ERROR_REVIEW_ADM_BOOKING = 'ERROR_REVIEW_ADM_BOOKING';
export const RESET_REVIEW_ADM_BOOKING = 'RESET_REVIEW_ADM_BOOKING';
export const RESET_STATUS_REVIEW_ADM_BOOKING =
  'RESET_STATUS_REVIEW_ADM_BOOKING';

export const START_UPLOAD_BERKAS_BOOKING = 'START_UPLOAD_BERKAS_BOOKING';
export const SUCCESS_UPLOAD_BERKAS_BOOKING = 'SUCCESS_UPLOAD_BERKAS_BOOKING';
export const ERROR_UPLOAD_BERKAS_BOOKING = 'ERROR_UPLOAD_BERKAS_BOOKING';
export const RESET_UPLOAD_BERKAS_BOOKING = 'RESET_UPLOAD_BERKAS_BOOKING';
export const RESET_STATUS_UPLOAD_BERKAS_BOOKING =
  'RESET_STATUS_UPLOAD_BERKAS_BOOKING';

export const START_FETCH_BOOKING_MINE = 'START_FETCH_BOOKING_MINE';
export const SUCCESS_FETCH_BOOKING_MINE = 'SUCCESS_FETCH_BOOKING_MINE';
export const ERROR_FETCH_BOOKING_MINE = 'ERROR_FETCH_BOOKING_MINE';

export const START_FETCH_BOOKING_DETAIL = 'START_FETCH_BOOKING_DETAIL';
export const SUCCESS_FETCH_BOOKING_DETAIL = 'SUCCESS_FETCH_BOOKING_DETAIL';
export const ERROR_FETCH_BOOKING_DETAIL = 'ERROR_FETCH_BOOKING_DETAIL';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_LIMIT = 'CHANGE_LIMIT';
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
