export const START_FETCH_PROJECT = 'START_FETCH_PROJECT';
export const SUCCESS_FETCH_PROJECT = 'SUCCESS_FETCH_PROJECT';
export const ERROR_FETCH_PROJECT = 'ERROR_FETCH_PROJECT';

export const START_FETCH_UNIT_PROJECT = 'START_FETCH_UNIT_PROJECT';
export const SUCCESS_FETCH_UNIT_PROJECT = 'SUCCESS_FETCH_UNIT_PROJECT';
export const ERROR_FETCH_UNIT_PROJECT = 'ERROR_FETCH_UNIT_PROJECT';

export const START_FETCH_PROJECT_DETAIL = 'START_FETCH_PROJECT_DETAIL';
export const SUCCESS_FETCH_PROJECT_DETAIL = 'SUCCESS_FETCH_PROJECT_DETAIL';
export const ERROR_FETCH_PROJECT_DETAIL = 'ERROR_FETCH_PROJECT_DETAIL';

export const CHANGE_PHASE = 'CHANGE_PHASE';
export const CHANGE_BLOCK = 'CHANGE_BLOCK';
export const CHANGE_UNIT = 'CHANGE_UNIT';

export const RESET_FILTER_PHASE_BLOCK_UNIT = 'RESET_FILTER_PHASE_BLOCK_UNIT';
